Repository JakobKlotz/lhasa-app, pull requests merged in 2025-05, with the labels that each got.

#7 Contribution guide
  CONTRIBUTING.md
  README.md
Labels: documentation

#5 Refactor: Split download logic to separate today/tomorrow downloads
  .gitignore
  backend/api/index.py
  backend/lhasa/download.py
  docker-compose.yaml
Labels: enhancement

#8 [0.2.0] Improved App Experience
  CHANGELOG.md
  README.md
  backend/Dockerfile
  backend/api/index.py
  backend/lhasa/download.py
  backend/pyproject.toml
  backend/uv.lock
  frontend/app/about/page.tsx
  frontend/app/api/download.ts
  frontend/app/api/files.tsx
  frontend/app/api/forecast.ts
  frontend/app/components/BackendStatusIndicator.tsx
  frontend/app/components/Footer.tsx
  frontend/app/components/Header.tsx
  frontend/app/components/TextHighlighter.tsx
  frontend/app/components/ThemeSwitcher.tsx
  frontend/app/contexts/ThemeContext.tsx
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/colors.yaml
  frontend/constants.tsx
  frontend/package-lock.json
  frontend/package.json
  screenshot/screen[0-1-0].png
  screenshot/screen[0-2-0].png
Labels: documentation, enhancement

#9 Global risk map
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  backend/api/index.py
  backend/lhasa/forecast.py
  backend/pyproject.toml
  backend/uv.lock
  frontend/.prettierrc.json
  frontend/app/about/page.tsx
  frontend/app/api/countries.ts
  frontend/app/api/forecast.ts
  frontend/app/components/Map.tsx
  frontend/app/components/MapLegend.tsx
  frontend/app/components/Statistics.tsx
  frontend/app/page.tsx
  frontend/package-lock.json
  frontend/package.json
  screenshot/screen[0-3-0].png
Labels: enhancement
